site_name: Coding for Journalists
site_description: A class to familiarize reporters with basic programming.
site_author: Alex Richards

repo_url: https://github.com/ireapps/coding-for-journalists/

pages:
- Main: index.md
- Setting up your computer: install.md
- Introduction: pt1.md
- Scraping the web: pt2.md
- Parsing text across lines: pt3.md
- Making a function: pt4.md
- Geocoding addresses: pt5.md
- APIs and databases: pt6.md
- Unlocking data from databases: pt7.md
- Cleaning data: pt8.md
- Other scrapes: pt9.md
- Text encoding and debugging: pt10.md
- Next steps: next_steps.md
theme: readthedocs

markdown_extensions:
    - admonition
    - codehilite
    
copyright: ©2015, <a href="http://www.ire.org">Investigative Reporters & Editors, Inc.</a>